databaseChangeLog:
  - include:
      file: config/liquibase/changelog/01_create_table_coins_usd.sql
  - include:
      file: config/liquibase/changelog/02_create_table_users.sql
  - include:
      file: config/liquibase/changelog/03_create_table_roles.sql
  - include:
      file: config/liquibase/changelog/04_create_table_user_roles.sql
  - include:
      file: config/liquibase/changelog/data/user_roles.sql
